### PR TITLE
add l10n messages caught by QA

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by peiying2** [comment]
@groovecoder this string needs to have a new ID. The change of content using the same string ID won't alert localizer the changes. Let's fix this one in the process. 

Any change of content from and older version to a new one requires a new string ID. We can add an extension of `-2` for updated string, depending on how many revision. Or simply use a new string ID. 

  "popupRemainingAliases": {
"message": "Remaining aliases: $REMAINING$",

**Comment by groovecoder** [comment]
@peiying2 - ? These are both brand new IDs. I don't see any other messages with `allowDataCollection` or `profilePageDefaulAliasLabelText` message IDs?

**Comment by peiying2** [comment]
> @peiying2 - ? These are both brand new IDs. I don't see any other messages with `allowDataCollection` or `profilePageDefaulAliasLabelText` message IDs?

Yes, the new strings look good. I approve the PR as it stands.

I was referring to the string change from yesterday. While you are working on this PR, let's update the string ID for the one I mentioned above. The changes introduced yesterday didn't trigger the change for the languages already localize. Or I can file an issue. Let me know what's best.

**Comment by groovecoder** [comment]
Oh I see. I included the fix for the `popupRemainingAliases` message - I restored the previous content under the previous message ID and added `popupRemainingAliases-2` message ID with the new content.

**Comment by peiying2** [comment]
Let's remove the old string if it's  no longer needed.

**Comment by groovecoder** [comment]
Removed `popupRemainingAliases` and kept `popupRemainingAliases-2`

**Review by peiying2 — APPROVED** [review]
Thanks for the fix! Looks good now.

**Pull request merged**
